### ISSUE TITLE
Add Models Definition In Readme

### ISSUE THREAD

**Issue by Zachdehooge** [Zachdehooge/NadoBot#20]
Add Models Definition In Readme with potential verbiage being:

The models can be any of the following:
models = 2024abs, 2024, 2022abs, 2022
it can also be left blank!

**Comment by Arch881010** [comment]
Been thinking about this... Maybe we should explain a little more than what's possible text here? Not everyone is going to understand what 2024abs or 2024 means by itself, I mean:
```env
MODELS=2024
```
Maybe we should say that these models are the year/type of models created by Nadocast?

**Comment by Zachdehooge** [comment]
Absolutely! Do you think commenting in the example.env would be best or in the README?

**Comment by Arch881010** [comment]
Possibly a note in example.env to see README.md, and explained in README.md as I figure people would read the README over the .env first.

**Comment by Arch881010** [comment]
This is pretty much done already..? Unless we are going to be more specific?

**Comment by Zachdehooge** [comment]
If there's nothing else you can think of I'm good with it! We can add more later as we see fit

**Comment by Arch881010** [comment]
Seems good with me!
