### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by JacksonDorschner** [Zachdehooge/NadoBot#6]
we need to make a nice looking help command, most likely using embeds.

**Comment by Arch881010** [comment]
![image](https://github.com/user-attachments/assets/d5990200-4f08-4f9f-b393-468bad1a8c8c)
There is already a built in help command, we either need to decide to leave it that way (as we can remove it and create our own help command) or our way. Need feedback. (The current $help command can be changed, where the command categories will have their own categories, or the info needed in the help command.)

**Comment by Arch881010** [comment]
![image](https://github.com/user-attachments/assets/698f3c7c-9a15-4923-adce-dd98608281e6)
This is an example of what we can do.

**Comment by JacksonDorschner** [comment]
although more work, what I think would look better is with an embed. I think most things should be using embeds because they are more user friendly with the "new" embed system, and look way better. I think you guys get the final call though.

**Comment by Arch881010** [comment]
I think the embed system would be better from a GUI standpoint.
I just know we have to write over the help command (as per discord.py docs).
We can use a new class to overwrite it ([checkout this stackoverflow example](https://stackoverflow.com/a/64094729)) or by first removing the command  (`bot.remove_command("help")`) then writing a new one (like any other command) (as per this [stackoverflow answer](https://stackoverflow.com/a/65089774)).

**Comment by JacksonDorschner** [comment]
you can see my incomplete branch that has started figuring out how to implement the embed

**Comment by Arch881010** [comment]
> you can see my incomplete branch that has started figuring out how to implement the embed

I do not see this branch.

**Comment by JacksonDorschner** [comment]
I have been pushing to my own fork lol, I will open another branch on this repo in a few hours.

**Comment by Arch881010** [comment]
> I have been pushing to my own fork lol, I will open another branch on this repo in a few hours.

After reading said fork, I don't think it's going in the direction I expected. Given sometimes there is more than 1 image.

**Comment by JacksonDorschner** [comment]
I was thinking we could have 2 images in one embed, and have a text field with a brief explanation of both images.

**Comment by Arch881010** [comment]
This will be completed after #18 is pulled by @Zachdehooge, now we have  #19 to follow up with.
