### ISSUE TITLE
Fetch Nadocast Data Not Displaying in Discord

### ISSUE THREAD

**Issue by Zachdehooge** [Zachdehooge/NadoBot#8]
![image](https://github.com/Zachdehooge/NadoBot/assets/47896974/218f225b-aa2d-4f8f-8a02-3c073d6b9613)
![image](https://github.com/Zachdehooge/NadoBot/assets/47896974/6cd9405e-9e0e-466c-b886-1f5335a8d6fb)

Nadocast data is downloading to local file system, but in discord it is saying it is not available

**Comment by Arch881010** [comment]
Odd. It was working previously.

**Comment by Arch881010** [comment]
![image](https://github.com/Zachdehooge/NadoBot/assets/111789310/1c8340a4-203a-44b8-a043-278f2eec3ce6)
This doesn't happen after pulling the repo and running again. It DOESN'T currently have the ability to delete the old folder.
